### ISSUE TITLE
More Than One Instance of BitCore Found

### ISSUE THREAD

**Issue by sriharikapu** [PaulLaux/eth-hot-wallet#19]
# Eth-Hot-Wallet

## Issue Type

- [ ✔︎ ] Bug

## Description

![screen shot 2019-01-04 at 9 42 38 am](https://user-images.githubusercontent.com/6247133/50688466-8d988a80-1060-11e9-8b9c-de4b0f391d01.png)

## Steps to reproduce

This issue is with v0.5 and up

# Versions

- ETH-Hot-Wallet (see `package.json`):
- Node/NPM: 8.6 + 
- Browser: chrome

**Comment by yongloon** [comment]
any solution?

**Comment by PaulLaux** [comment]
Please provide reproduction steps. I'm not getting this error (see https://eth-hot-wallet.com/)

**Comment by yongloon** [comment]
1) npm install
2) npm run start

**Comment by thedon-chris** [comment]
Try running it with `yarn install`

**Comment by thedon-chris** [comment]
> Try running it with `yarn install`

Running with `yarn` instead of `npm` solved issue

**Comment by zzlune** [comment]
1、 As the issue(https://github.com/bitpay/bitcore/issues/1454) describes, you can go to the file node_modules/bitcore-mnemonic/node_modules/index.js,and change the code 
```javascript
bitcore.versionGuard = function (version) {
  if (version !== undefined) {
    var message = 'More than one instance of bitcore-lib found. ' +
      'Please make sure to require bitcore-lib and check that submodules do' +
      ' not also include their own bitcore-lib dependency.';
    throw new Error(message);
  }
};
```
to
```javascript
bitcore.versionGuard = function (version) {
  return;
  if (version !== undefined) {
    var message = 'More than one instance of bitcore-lib found. ' +
      'Please make sure to require bitcore-lib and check that submodules do' +
      ' not also include their own bitcore-lib dependency.';
    throw new Error(message);
  }
};
```
2、Go to the root directory, and run the command
`npm run build:dll` 
`npm run start`
  Then it has already fixed

**Comment by sriharikapu** [comment]
@zctocm Your solution works. Thanks a lot.
