### ISSUE TITLE
Error when locked wallet don't disappear after a while

### ISSUE THREAD

**Issue by citizen-z** [PaulLaux/eth-hot-wallet#3]
# ETH-HOT-WALLET - Ethereum web wallet

## Issue Type

- [x] Bug 

## Description

(Add images if possible)

## Steps to reproduce
- create new wallet
- lock wallet
- add new address 

![eth-hot-wallet](https://user-images.githubusercontent.com/11316974/33806568-d051c5ce-ddd2-11e7-9c84-992d05d719bd.JPG)

- ETH-Hot-Wallet (see `package.json`):
- Node/NPM:
- Browser:

**Comment by PaulLaux** [comment]
Resolved in last update
